### ISSUE TITLE
Getting errors trying to run the demo files (windows)

### ISSUE THREAD

**Issue by DaftMav** [talmobi/twitch-webchat#1]
First of all, I'm new to using phantomjs, and I've googled these phantomjs errors for hours now but I'm not getting anywhere. So a little info on what I did from scratch:

I've installed PhantomJS and added it to windows' system environments path, and downloaded twitch-webchat from git source and did npm install. It correctly detects my PhantomJS in PATH and installs everything without any error.

However running any of the demos in the test and demo folders, I get these errors:

```
d:\webdev\twitch-webchat-master\test>phantomjs basic-test.js
Error: Cannot find module 'path'

  phantomjs://platform/bootstrap.js:299 in require
  phantomjs://platform/bootstrap.js:263 in require
  phantomjs://platform/twitch-webchat.js:8
Error: Cannot find module 'assert'

  phantomjs://platform/bootstrap.js:299 in require
  phantomjs://platform/bootstrap.js:263 in require
```

And then it just hangs until I ctrl-c out of it. 

I've been able to get rid of the error lines by adding phantom.libraryPath to the various require lines like this:

```
var assert = require(phantom.libraryPath + 'assert');
var request = require(phantom.libraryPath + 'request');
```

(I guess PhantomJS is not as platform independent as advertised?)
But that leaves the bootstrap errors which are still a problem. I'm not sure if it's supposed to install bootstrap into node-modules? Because I can't find any bootstrap files anywhere.

**Comment by talmobi** [comment]
It looks like you need to disable web security when running phantomjs. If you see [here](https://github.com/talmobi/twitch-webchat/blob/master/twitch-webchat.js#L15) I also pass in the `--web-security=false` command line argument to phantomjs (running as a childProcess.spawn) to enable cross origin resources from loading on the page.

So try `phantomjs --web-security=false basic-test.js`

More info on phantomjs command line arguments (including --web-security):  http://phantomjs.org/api/command-line.html

`--web-security=[true|false] enables web security and forbids cross-domain XHR (default is true). Also accepted: [yes|no].`

Also, the twitch messaging format has changed somewhat so the tests are failling, I should update them to be more flexible.

Also since twitch-webchat uses phantomjs-prebuilt npm package (that installs phantomjs for you when you npm install it) --you may need to run `npm rebuild` so that it detects which OS you are and uses the correct binrary (I should add it as a postinstall script probably). See here: https://github.com/Medium/phantomjs#cross-platform-repositories

**Comment by talmobi** [comment]
Oh and also, the tests are supposed to be run with nodejs, not phantomjs.

[EDIT]: twitch-webchat wraps around and hides the fact that is is using phantomjs under the hood for you. This is intended.

**Comment by DaftMav** [comment]
> Oh and also, the tests are supposed to be run with nodejs, not phantomjs.

Argh.. well that makes things a lot clearer, I was using phantomjs to start this all while thinking node/npm was just the package manager/downloader (literally the description on the frontpage) and PhantomJS the thing that runs it all. This key bit of info is not found in any of the NPM/PhantomJS starting guides I read. As suggested in the PhantomJS documentation I thought installing and adding it to the system path was the best and most convenient way to use it from the command line but clearly I didn't fully understand the difference between NPM/Node and PhantomJS.

So I've got it all working now. I deleted everything and started from scratch, this time just using npm and let it use the phantomjs-prebuilt instead. Just letting you know one of the installation methods doesn't work correctly:

Using `npm install twitch-webchat` it ends with the errors below, an empty project directory with just a node_modules directory. I think the twitch-webchat files are supposed to be installed in the directory I run the command in (d:\webdev\test2\), but they're added in d:\webdev\test2\node_modules\twitch-webchat\ instead, so at the end it can't find the package.json. Maybe there's a installation config going wrong?

```
npm WARN enoent ENOENT: no such file or directory, open 'd:\webdev\test2\package.json'
npm WARN node-version No description
npm WARN node-version No repository field.
npm WARN node-version No README data
npm WARN node-version No license field.
```

I did it again from git/source with just `npm install` and everything seems to install correctly that way.

Now using `npm test` instead of phantomjs, it indeed gives some failing errors but runs and that's luckily not what I wanted to use anyway. I ran the demo with `node server-demo.js` and it all works. I guess for people who know how to node this is obvious but for newcomers it could perhaps be useful to include in the 'how to use' section? I think I went wrong when I assumed I had to download PhantomJS myself.

Thanks for the help and sorry about the confusion, I hate to wrongfully make issue tickets but wasn't able to figure this one out. Still baffled how none of the guides I found included any clear explanation of differences between node/npm/PhanthomJS.

**Comment by talmobi** [comment]
`npm install ...` by itself searches for a `package.json` file and installs them inside that directory under a `node_modules` directory.

So if you want to create a new project, you first need to run `npm init`, `npm init -y` or simply `echo "{}" > package.json` that will create a `package.json` file in your current directory. Then when you run `npm install ...` under that directory it will install them in the correct place.

Pretty basic NodeJS stuff. (:

`phantomjs-prebuilt` is just a convenient way for installing phantoms - but not necessary of course. You are supposed to run phantomjs specific scripts with the `phantomjs` command line tool (see: https://github.com/talmobi/twitch-webchat/blob/master/index.phantom.js and https://github.com/talmobi/twitch-webchat/blob/master/twitch-webchat.js#L40) - NodeJS script files will not work - phantomjs is a completely different environment than NodeJS (even though they both use javascript and similar syntax)
